// Safe to edit manually: cluster definitions and 90-day content opportunity backlog.

import type {
  ContentAuditNote,
  ContentOpportunityCandidate,
  OptimizationPriority,
  QueryClusterDefinition,
} from "@/content/optimization/types";

function cluster(
  id: QueryClusterDefinition["id"],
  label: string,
  clusterGroup: QueryClusterDefinition["clusterGroup"],
  intent: QueryClusterDefinition["intent"],
  priority: OptimizationPriority,
  preferredPageType: QueryClusterDefinition["preferredPageType"],
  preferredLocaleEmphasis: QueryClusterDefinition["preferredLocaleEmphasis"],
  queryPatterns: string[],
  risingImpressionsLowClicksAction: string,
  risingClicksLowConversionsAction: string,
): QueryClusterDefinition {
  return {
    id,
    label,
    clusterGroup,
    intent,
    priority,
    preferredPageType,
    preferredLocaleEmphasis,
    queryPatterns,
    risingImpressionsLowClicksAction,
    risingClicksLowConversionsAction,
  };
}

function candidate(
  input: ContentOpportunityCandidate,
): ContentOpportunityCandidate {
  return input;
}

export const QUERY_CLUSTERS: QueryClusterDefinition[] = [
  cluster(
    "custom_web_application_development",
    "Custom web application development",
    "service_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "service",
    "both",
    ["vyvoj webovych aplikaci na miru", "webove aplikace na miru", "custom web application development", "custom web app development"],
    "Tune title/meta/H1 on the core service page, tighten the intro, and add FAQ around scope, MVP, and fit.",
    "Keep the service page commercial, add stronger fit / not-fit, and route clicks into inquiry and process pages.",
  ),
  cluster(
    "internal_tools_development",
    "Internal tools development",
    "service_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "service",
    "both",
    ["interni system na miru", "interni nastroj", "internal tools development", "internal tool development"],
    "Strengthen commercial framing and add supporting sections about replacing spreadsheets, approvals, and multi-role workflows.",
    "Improve CTAs and add use-case links so traffic lands in inquiry instead of only reading support content.",
  ),
  cluster(
    "existing_app_takeover",
    "Existing app takeover",
    "service_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "service",
    "both",
    ["prevzeti aplikace", "prevzeti existujici aplikace", "existing app takeover", "app takeover"],
    "Tighten risk-first messaging and FAQ around access, discovery, and takeover audit.",
    "Move more traffic into inquiry, case studies, and takeover checklists instead of letting it stop on informational sections.",
  ),
  cluster(
    "automations_and_integrations",
    "Automations and integrations",
    "service_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "service",
    "both",
    ["automatizace a integrace", "integrace systemu", "automations and integrations", "system integrations"],
    "Improve query-to-page match with stronger intro, process examples, and FAQ about API, workflow, and ownership.",
    "Add clearer next-step CTA and link into automation discovery/template assets.",
  ),
  cluster(
    "contract_development_support",
    "Contract development support",
    "service_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "service",
    "both",
    ["spoluprace na kontrakt", "seniorni kapacita do tymu", "contract development support", "senior contract capacity"],
    "Rewrite hero and meta to match the highest-performing contract terms without drifting into recruiter language.",
    "Tighten fit / not-fit framing and move traffic into inquiry with explicit ownership language.",
  ),
  cluster(
    "slow_app",
    "Slow application",
    "problem_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "problem",
    "cs_primary",
    ["aplikace je pomala", "slow business app", "slow web app"],
    "Add sharper answer-first opening and stronger proof sections around bottlenecks, release risk, and stabilisation.",
    "If conversion is weak, add clearer service linkage to app takeover and stabilisation guides.",
  ),
  cluster(
    "hard_to_maintain_app",
    "Hard to maintain application",
    "problem_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "problem",
    "both",
    ["tezko se udrzuje", "legacy app maintenance", "hard to maintain app"],
    "Expand supporting sections around technical debt, ownership, and incremental stabilisation.",
    "Push traffic toward takeover and rewrite-vs-incremental comparison pages.",
  ),
  cluster(
    "app_takeover_problem",
    "Take over an existing application",
    "problem_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "problem",
    "both",
    ["potrebujeme prevzit aplikaci", "take over an existing app", "inherited app"],
    "Strengthen symptoms, buyer risk framing, and FAQ around missing access and release knowledge.",
    "Improve conversion path into service takeover and inquiry pages.",
  ),
  cluster(
    "rescue_incomplete_project",
    "Rescue incomplete project",
    "problem_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "problem",
    "both",
    ["zachranit rozdelany projekt", "rescue incomplete project", "stalled software project"],
    "Sharpen hero copy and add proof-like sections about scope drift, trust loss, and first reset milestone.",
    "Drive more traffic into takeover service and contract-support inquiry paths.",
  ),
  cluster(
    "senior_contract_capacity",
    "Senior contract capacity",
    "problem_intent",
    "commercial",
    "HIGH_PRIORITY_MONEY",
    "problem",
    "both",
    ["chybi seniorni kapacita", "senior contract capacity", "senior contract developer"],
    "Tune title/meta toward contract-support language and clarify who this is for and not for.",
    "Improve CTA and comparison links so the page converts into contract-support discussions.",
  ),
  cluster(
    "client_portal_problem",
    "Need a client portal",
    "problem_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "problem",
    "both",
    ["potrebujeme klientsky portal", "need a client portal", "client portal development"],
    "Add stronger answer-first framing around documents, status visibility, and self-service.",
    "Route traffic into custom web app service, B2B portal use case, and inquiry.",
  ),
  cluster(
    "custom_vs_saas",
    "Custom vs SaaS",
    "comparison_intent",
    "decision",
    "HIGH_PRIORITY_SUPPORT",
    "comparison",
    "both",
    ["custom vs saas", "vyvoj na miru vs saas", "build vs buy software"],
    "Rewrite title/meta and top decision block to align with the exact trade-off users are searching for.",
    "Tighten the next-step CTA and route into internal tools or custom app service pages.",
  ),
  cluster(
    "contractor_vs_agency",
    "Contractor vs agency",
    "comparison_intent",
    "decision",
    "HIGH_PRIORITY_SUPPORT",
    "comparison",
    "both",
    ["contractor vs agency", "externi vyvojar vs agentura", "contract developer vs agency"],
    "Make the direct answer more explicit and align headline wording with the winning query pattern.",
    "Improve follow-through into contract-support and senior-capacity problem pages.",
  ),
  cluster(
    "nextjs_vs_spa",
    "Next.js vs SPA",
    "comparison_intent",
    "decision",
    "MEDIUM_CLUSTER_EXPANSION",
    "comparison",
    "en_selective",
    ["nextjs vs spa", "nextjs vs react spa", "nextjs vs spa for business apps"],
    "If impressions rise but clicks stay weak, narrow the copy harder toward business apps instead of generic frontend traffic.",
    "If clicks rise but conversion is weak, add clearer internal links into commercial service pages or consider narrowing intent with noindex later.",
  ),
  cluster(
    "rewrite_vs_incremental",
    "Rewrite vs incremental improvement",
    "comparison_intent",
    "decision",
    "HIGH_PRIORITY_SUPPORT",
    "comparison",
    "both",
    ["rewrite vs incremental", "rewrite vs postupny rozvoj", "refactor vs rewrite app"],
    "Strengthen the short answer and rewrite the title to match the exact delivery dilemma collecting impressions.",
    "Route traffic to takeover, rescue-project problem pages, and takeover pricing guides.",
  ),
  cluster(
    "internal_tool_vs_saas",
    "Internal tool vs SaaS",
    "comparison_intent",
    "decision",
    "HIGH_PRIORITY_SUPPORT",
    "comparison",
    "cs_primary",
    ["interni system misto saas", "internal tool vs saas", "internal tool better than saas"],
    "If impressions rise, expand comparison depth and link from internal-tools service and guide pages.",
    "If clicks rise but leads stay weak, add clearer commercial CTA and stronger examples of workflow fit.",
  ),
  cluster(
    "estimate_project",
    "Estimate project / price takeover",
    "guide_intent",
    "decision",
    "HIGH_PRIORITY_SUPPORT",
    "guide",
    "both",
    ["jak nacenit projekt", "jak nacenit prevzeti aplikace", "how to price an app takeover"],
    "Tune the intro and title to the precise estimate-related query and add FAQ on uncertainty and first-phase pricing.",
    "Add stronger links into inquiry, takeover service, and supporting templates.",
  ),
  cluster(
    "scope_custom_development",
    "Scope custom development",
    "guide_intent",
    "decision",
    "HIGH_PRIORITY_SUPPORT",
    "guide",
    "both",
    ["jak zadat vyvoj", "scope custom web application", "web app project brief"],
    "Expand the answer-first intro and FAQ around scope, MVP, and role definition.",
    "Push traffic into brief templates and inquiry instead of keeping it purely educational.",
  ),
  cluster(
    "assess_project_fit",
    "Assess project fit",
    "guide_intent",
    "decision",
    "MEDIUM_CLUSTER_EXPANSION",
    "guide",
    "both",
    ["jak poznat fit projektu", "when custom development makes sense", "how to know project fit"],
    "Clarify fit / not-fit and rewrite the first screen to match commercial buyer language.",
    "If conversion remains low, merge weaker overlap into a stronger commercial guide or hub.",
  ),
  cluster(
    "take_over_app",
    "Take over an app safely",
    "guide_intent",
    "decision",
    "HIGH_PRIORITY_SUPPORT",
    "guide",
    "both",
    ["jak prevzit aplikaci", "take over an app safely", "app takeover audit"],
    "Add more explicit takeover checklist and audit language in the intro and FAQ.",
    "Send traffic into takeover service, checklist assets, and inquiry.",
  ),
  cluster(
    "plan_mvp",
    "Plan MVP",
    "guide_intent",
    "decision",
    "MEDIUM_CLUSTER_EXPANSION",
    "guide",
    "both",
    ["jak planovat mvp", "plan mvp web application", "mvp planning"],
    "Expand around first-release boundaries, roles, and discovery inputs if impressions become relevant.",
    "If clicks stay informational only, route harder into custom-development service and brief assets.",
  ),
  cluster(
    "client_portal_use_case",
    "Client portal use case",
    "use_case_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "use_case",
    "both",
    ["klientsky portal", "client portal", "customer portal development"],
    "Add deeper examples of document flow, status visibility, and self-service scenarios.",
    "Link directly into portal-related services and inquiry if clicks rise.",
  ),
  cluster(
    "internal_system_use_case",
    "Internal system use case",
    "use_case_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "use_case",
    "cs_primary",
    ["interni system", "internal system", "operations system"],
    "Expand with more operational examples and route into internal-tools and scope-worksheet pages.",
    "If conversion stays weak, tighten the commercial CTA and add clearer buyer fit language.",
  ),
  cluster(
    "reporting_dashboard_use_case",
    "Reporting dashboard use case",
    "use_case_intent",
    "commercial",
    "MEDIUM_CLUSTER_EXPANSION",
    "use_case",
    "both",
    ["reporting dashboard", "dashboard pro management", "management dashboard"],
    "Expand around data trust, KPI ownership, and management use cases when impressions start to climb.",
    "If clicks do not lead to inquiry, push more clearly into internal-tools and integration services.",
  ),
  cluster(
    "workflow_app_use_case",
    "Workflow app use case",
    "use_case_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "use_case",
    "cs_primary",
    ["workflow aplikace", "workflow app", "workflow automation tools"],
    "Add more examples of multi-role flow, bottlenecks, and exception handling.",
    "Use stronger CTA language pointing into internal tools, automations, and inquiry.",
  ),
  cluster(
    "b2b_portal_use_case",
    "B2B portal use case",
    "use_case_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "use_case",
    "both",
    ["b2b portal", "b2b klientsky portal", "partner portal"],
    "Expand around partner self-service, document exchange, and account workflows.",
    "If conversion is weak, route more aggressively into custom web app service and portal problem pages.",
  ),
  cluster(
    "approval_system_use_case",
    "Approval system use case",
    "use_case_intent",
    "commercial",
    "HIGH_PRIORITY_SUPPORT",
    "use_case",
    "cs_primary",
    ["schvalovaci system", "approval system", "internal approval workflow"],
    "Add more concrete examples of approvals, audit trail, and exception paths.",
    "If leads stay weak, emphasize internal-tools service and business-process fit more directly.",
  ),
  cluster(
    "nextjs_business_apps",
    "Next.js for business apps",
    "technology_intent",
    "research",
    "MEDIUM_CLUSTER_EXPANSION",
    "technology",
    "en_selective",
    ["nextjs for business apps", "nextjs pro byznys aplikace", "nextjs business applications"],
    "Keep the page business-narrow and avoid drifting into generic framework content.",
    "If clicks do not convert, strengthen commercial links or consider narrowing/noindex review later.",
  ),
  cluster(
    "typescript_large_projects",
    "TypeScript for large projects",
    "technology_intent",
    "research",
    "LOW_PRIORITY_EXPERIMENT",
    "technology",
    "en_selective",
    ["typescript for large projects", "typescript pro vetsi projekty"],
    "Only expand if the query clearly stays tied to business-app delivery, not broad developer education.",
    "If traffic is broad and weakly commercial, keep selective or consider noindex/merge review.",
  ),
  cluster(
    "api_integrations",
    "API integrations",
    "technology_intent",
    "research",
    "HIGH_PRIORITY_SUPPORT",
    "technology",
    "both",
    ["api integrace", "api integrations", "system api integration"],
    "Expand around discovery, ownership, failure states, and links to service and template pages.",
    "If clicks rise but leads stay weak, route more clearly into automations and inquiry pages.",
  ),
  cluster(
    "postgresql_internal_tools",
    "PostgreSQL for internal tools",
    "technology_intent",
    "research",
    "LOW_PRIORITY_EXPERIMENT",
    "technology",
    "en_selective",
    ["postgresql for internal tools", "postgresql pro interni systemy"],
    "Only expand if it remains tightly tied to internal-tool architecture and buyer intent.",
    "If broad technical traffic appears with weak commercial fit, keep selective or review for merge/noindex.",
  ),
];

export const REWRITE_CANDIDATES: ContentOpportunityCandidate[] = [
  candidate({
    id: "rewrite-cs-home",
    candidateType: "rewrite",
    locale: "cs",
    clusterId: "custom_web_application_development",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/cs",
    rationale: "Primary Czech money page. It should be continuously tuned against the strongest buyer-intent queries and Search Console snippets.",
    triggerSignals: ["High impressions but weak homepage CTR", "Broad service-intent queries landing on homepage", "Inquiry conversion weaker than service pages"],
    supportingLinks: ["/cs/sluzby", "/cs/popsat-projekt"],
  }),
  candidate({
    id: "rewrite-en-home",
    candidateType: "rewrite",
    locale: "en",
    clusterId: "contract_development_support",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/en",
    rationale: "Primary English entry point should stay narrower, premium, and contract-delivery focused.",
    triggerSignals: ["English service queries rising", "Clicks with weak contract-support conversion", "Broad generic dev traffic creeping in"],
    supportingLinks: ["/en/services", "/en/discuss-your-project"],
  }),
  candidate({
    id: "rewrite-cs-custom-app-service",
    candidateType: "rewrite",
    locale: "cs",
    clusterId: "custom_web_application_development",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/cs/sluzby/vyvoj-webovych-aplikaci-na-miru",
    rationale: "Core Czech service page for commercial demand capture.",
    triggerSignals: ["Money-term impressions rise", "CTR underperforms service cluster average", "Clicks do not reach inquiry"],
    supportingLinks: ["/cs/popsat-projekt", "/cs/srovnani/vyvoj-na-miru-vs-saas"],
  }),
  candidate({
    id: "rewrite-en-custom-app-service",
    candidateType: "rewrite",
    locale: "en",
    clusterId: "custom_web_application_development",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/en/services/custom-web-application-development",
    rationale: "English money page for premium project-intent traffic.",
    triggerSignals: ["Commercial impressions rise", "Low CTR on custom-web-app queries", "Weak inquiry conversion"],
    supportingLinks: ["/en/discuss-your-project", "/en/comparisons/custom-web-app-vs-saas-tool"],
  }),
  candidate({
    id: "rewrite-cs-takeover-service",
    candidateType: "rewrite",
    locale: "cs",
    clusterId: "existing_app_takeover",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace",
    rationale: "One of the strongest conversion pages for takeover/rescue demand.",
    triggerSignals: ["Takeover impressions rise", "Rescue queries land here with low CTR", "Users click but stall before inquiry"],
    supportingLinks: ["/cs/popsat-projekt", "/cs/pruvodce/jak-prevzit-existujici-aplikaci-bez-rizika"],
  }),
  candidate({
    id: "rewrite-en-takeover-service",
    candidateType: "rewrite",
    locale: "en",
    clusterId: "existing_app_takeover",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/en/services/existing-app-takeover",
    rationale: "High-value English page for inherited-app and takeover traffic.",
    triggerSignals: ["Takeover query growth", "Low CTR on inherited-app queries", "Weak click-to-inquiry flow"],
    supportingLinks: ["/en/discuss-your-project", "/en/guides/how-to-take-over-an-existing-app-safely"],
  }),
  candidate({
    id: "rewrite-cs-automation-service",
    candidateType: "rewrite",
    locale: "cs",
    clusterId: "automations_and_integrations",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/cs/sluzby/automatizace-a-integrace",
    rationale: "Strong commercial landing flow with clear revenue-adjacent buyer intent.",
    triggerSignals: ["Integration/automation impressions rise", "Low CTR from API or workflow queries", "Clicks fail to reach inquiry"],
    supportingLinks: ["/cs/sablony/discovery-checklist-pro-automatizace", "/cs/popsat-projekt"],
  }),
  candidate({
    id: "rewrite-cs-app-takeover-problem",
    candidateType: "rewrite",
    locale: "cs",
    clusterId: "app_takeover_problem",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/cs/problemy/potrebujeme-prevzit-rozpracovanou-aplikaci",
    rationale: "A strong entry page for problem-shaped takeover demand that should route into the commercial path faster.",
    triggerSignals: ["Problem-intent impressions rise", "Weak CTR on takeover problem terms", "Service page gets stronger conversion than problem page"],
    supportingLinks: ["/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace", "/cs/popsat-projekt"],
  }),
  candidate({
    id: "rewrite-cs-custom-vs-saas",
    candidateType: "rewrite",
    locale: "cs",
    clusterId: "custom_vs_saas",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/cs/srovnani/vyvoj-na-miru-vs-saas",
    rationale: "Top comparison page with high potential to create mid-funnel commercial demand.",
    triggerSignals: ["Comparison impressions rise", "CTR problem on build-vs-buy queries", "Clicks do not route into services"],
    supportingLinks: ["/cs/sluzby/vyvoj-webovych-aplikaci-na-miru", "/cs/popsat-projekt"],
  }),
  candidate({
    id: "rewrite-cs-inquiry",
    candidateType: "rewrite",
    locale: "cs",
    clusterId: "assess_project_fit",
    priority: "HIGH_PRIORITY_MONEY",
    targetAction: "REWRITE_EXISTING",
    currentPath: "/cs/popsat-projekt",
    rationale: "Critical conversion page. Messaging should track the highest-performing commercial entry paths.",
    triggerSignals: ["Clicks rise across money pages but inquiry conversion lags", "Contract-support traffic stalls before submit", "Mismatch between landing-page promise and inquiry framing"],
    supportingLinks: ["/cs", "/cs/jak-spoluprace-probiha"],
  }),
];

export const EXPANSION_CANDIDATES: ContentOpportunityCandidate[] = [
  candidate({
    id: "expand-cs-services-hub",
    candidateType: "expand",
    locale: "cs",
    clusterId: "custom_web_application_development",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/cs/sluzby",
    rationale: "Core Czech hub should absorb more service-intent impressions and route traffic into the top money pages.",
    triggerSignals: ["Hub impressions rise", "Top services need stronger internal support", "Users enter through hub instead of leaf pages"],
    supportingLinks: ["/cs/sluzby/vyvoj-webovych-aplikaci-na-miru", "/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace"],
  }),
  candidate({
    id: "expand-en-services-hub",
    candidateType: "expand",
    locale: "en",
    clusterId: "contract_development_support",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/en/services",
    rationale: "English service hub should stay selective and route into the best premium-fit pages.",
    triggerSignals: ["English service impressions rise", "Users enter through hub queries", "Need clearer top-pick ordering"],
    supportingLinks: ["/en/services/existing-app-takeover", "/en/contract-development-support"],
  }),
  candidate({
    id: "expand-cs-slow-app-problem",
    candidateType: "expand",
    locale: "cs",
    clusterId: "slow_app",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/cs/problemy/aplikace-je-pomala-a-tezko-se-udrzuje",
    rationale: "Problem page with likely long-tail potential around performance, maintainability, and stabilisation.",
    triggerSignals: ["Relevant impressions rise", "Queries diversify around slow / unstable app wording", "Users need more proof before clicking through"],
    supportingLinks: ["/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace", "/cs/pruvodce/jak-stabilizovat-pomalou-aplikaci"],
  }),
  candidate({
    id: "expand-en-senior-capacity-problem",
    candidateType: "expand",
    locale: "en",
    clusterId: "senior_contract_capacity",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/en/problems/we-need-senior-contract-capacity",
    rationale: "Good English problem page for premium contract-support demand.",
    triggerSignals: ["Senior contract queries rise", "Traffic clicks but does not reach inquiry", "Need stronger proof and not-fit language"],
    supportingLinks: ["/en/contract-development-support", "/en/discuss-your-project"],
  }),
  candidate({
    id: "expand-cs-guide-scope",
    candidateType: "expand",
    locale: "cs",
    clusterId: "scope_custom_development",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/cs/pruvodce/jak-zadat-vyvoj-webove-aplikace",
    rationale: "Likely winner for broad but still commercial guide intent.",
    triggerSignals: ["Guide impressions rise", "Users ask scope / MVP / brief-related questions", "Templates need stronger parent page support"],
    supportingLinks: ["/cs/sablony/brief-na-webovou-aplikaci", "/cs/popsat-projekt"],
  }),
  candidate({
    id: "expand-en-guide-takeover-pricing",
    candidateType: "expand",
    locale: "en",
    clusterId: "estimate_project",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/en/guides/how-to-price-an-app-takeover",
    rationale: "Strong commercial guide candidate for takeover decision traffic.",
    triggerSignals: ["Pricing queries rise", "Users need stronger first-phase explanation", "Need clearer CTA to inquiry or audit"],
    supportingLinks: ["/en/services/existing-app-takeover", "/en/templates/app-takeover-checklist"],
  }),
  candidate({
    id: "expand-cs-b2b-portal-usecase",
    candidateType: "expand",
    locale: "cs",
    clusterId: "b2b_portal_use_case",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/cs/priklady/b2b-klientsky-portal",
    rationale: "Likely to collect high-intent portal traffic if query variants start clustering.",
    triggerSignals: ["Portal impressions rise", "Need more supporting scenarios", "Problem page and use-case page begin to share query family"],
    supportingLinks: ["/cs/sluzby/vyvoj-webovych-aplikaci-na-miru", "/cs/problemy/potrebujeme-klientsky-portal"],
  }),
  candidate({
    id: "expand-cs-templates-hub",
    candidateType: "expand",
    locale: "cs",
    clusterId: "scope_custom_development",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/cs/sablony",
    rationale: "Utility hub can become a stronger entry page once template traffic starts showing up.",
    triggerSignals: ["Template impressions rise", "Several assets start collecting clicks", "Need stronger top-pick curation"],
    supportingLinks: ["/cs/sablony/brief-na-webovou-aplikaci", "/cs/sablony/checklist-prevzeti-aplikace"],
  }),
  candidate({
    id: "expand-cs-problems-hub",
    candidateType: "expand",
    locale: "cs",
    clusterId: "rescue_incomplete_project",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/cs/problemy",
    rationale: "Problem hub should grow as a major commercial landing page for buyer-intent search patterns.",
    triggerSignals: ["Problem pages begin sharing impressions", "Need better prioritisation of top problems", "New clusters need a stronger parent page"],
    supportingLinks: ["/cs/problemy/potrebujeme-zachranit-rozdelany-projekt", "/cs/problemy/chybi-seniorni-kapacita-do-tymu"],
  }),
  candidate({
    id: "expand-en-api-tech-page",
    candidateType: "expand",
    locale: "en",
    clusterId: "api_integrations",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "EXPAND_EXISTING",
    currentPath: "/en/technology/api-integrations",
    rationale: "Technology-support page worth expanding only if it keeps a commercial integration signal.",
    triggerSignals: ["API integration impressions rise", "Traffic remains business-process oriented", "Template/service cluster needs stronger supporting content"],
    supportingLinks: ["/en/services/automations-and-integrations", "/en/templates/api-integration-checklist"],
  }),
];

export const NEW_PAGE_CANDIDATES: ContentOpportunityCandidate[] = [
  candidate({
    id: "new-cs-legacy-modernization-problem",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "hard_to_maintain_app",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/problemy/potrebujeme-modernizovat-legacy-aplikaci",
    proposedPageType: "problem",
    rationale: "Strong Czech problem-intent angle adjacent to takeover and stabilisation.",
    triggerSignals: ["Legacy modernization queries appear in GSC", "Slow/maintainability page broadens", "Rewrite-vs-incremental queries overlap"],
    supportingLinks: ["/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace", "/cs/srovnani/rewrite-vs-postupny-rozvoj-aplikace"],
  }),
  candidate({
    id: "new-en-legacy-modernization-problem",
    candidateType: "new_page",
    locale: "en",
    clusterId: "hard_to_maintain_app",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/problems/we-need-to-modernize-a-legacy-business-app",
    proposedPageType: "problem",
    rationale: "Selective English page for buyer-intent legacy modernization demand.",
    triggerSignals: ["English legacy-business-app queries show commercial fit", "Existing slow-app page starts ranking for modernization terms"],
    supportingLinks: ["/en/services/existing-app-takeover", "/en/comparisons/rewrite-vs-incremental-app-improvement"],
  }),
  candidate({
    id: "new-cs-replace-spreadsheets-problem",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "internal_tools_development",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/problemy/potrebujeme-nahradit-excel-ve-firemnim-procesu",
    proposedPageType: "problem",
    rationale: "Very plausible Czech buyer query for internal-tool demand.",
    triggerSignals: ["Spreadsheet replacement queries rise", "Internal-system service starts collecting spreadsheet terms"],
    supportingLinks: ["/cs/sluzby/interni-systemy-na-miru", "/cs/sablony/scope-worksheet-pro-interni-system"],
  }),
  candidate({
    id: "new-en-replace-spreadsheets-problem",
    candidateType: "new_page",
    locale: "en",
    clusterId: "internal_tools_development",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/problems/we-need-to-replace-spreadsheets-in-an-operational-process",
    proposedPageType: "problem",
    rationale: "Selective English support page if spreadsheet-to-tool demand appears with business intent.",
    triggerSignals: ["Spreadsheet replacement queries appear with ops/product wording", "Internal-tool pages rank for those terms"],
    supportingLinks: ["/en/services/internal-tools-development", "/en/templates/internal-tool-scope-worksheet"],
  }),
  candidate({
    id: "new-cs-release-process-problem",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "existing_app_takeover",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/problemy/release-proces-aplikace-je-nespolehlivy",
    proposedPageType: "problem",
    rationale: "Natural adjacent problem cluster for takeover, stabilisation, and senior ownership.",
    triggerSignals: ["Release risk queries rise", "Takeover pages collect deploy/release language"],
    supportingLinks: ["/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace", "/cs/spoluprace-na-kontrakt"],
  }),
  candidate({
    id: "new-en-release-process-problem",
    candidateType: "new_page",
    locale: "en",
    clusterId: "existing_app_takeover",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/problems/our-release-process-is-fragile-and-risky",
    proposedPageType: "problem",
    rationale: "English problem page for release-risk takeover scenarios.",
    triggerSignals: ["Fragile release queries emerge", "Existing takeover traffic starts splitting into release-risk terms"],
    supportingLinks: ["/en/services/existing-app-takeover", "/en/contract-development-support"],
  }),
  candidate({
    id: "new-cs-internal-tool-vs-spreadsheets",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "internal_tool_vs_saas",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/srovnani/interni-system-vs-excel-a-email",
    proposedPageType: "comparison",
    rationale: "Likely stronger Czech decision page than broad generic internal-tool content.",
    triggerSignals: ["Spreadsheet/email workaround queries rise", "Internal system pages collect comparison-style impressions"],
    supportingLinks: ["/cs/sluzby/interni-systemy-na-miru", "/cs/pruvodce/kdy-dava-smysl-interni-system-misto-saas"],
  }),
  candidate({
    id: "new-en-internal-tool-vs-spreadsheets",
    candidateType: "new_page",
    locale: "en",
    clusterId: "internal_tool_vs_saas",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/comparisons/internal-tool-vs-spreadsheets-and-email",
    proposedPageType: "comparison",
    rationale: "Selective English comparison page if spreadsheet-replacement traffic proves commercial.",
    triggerSignals: ["English spreadsheet-replacement comparison queries appear", "Internal tools cluster expands in GSC"],
    supportingLinks: ["/en/services/internal-tools-development", "/en/templates/internal-tool-scope-worksheet"],
  }),
  candidate({
    id: "new-cs-contractor-vs-hire",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "senior_contract_capacity",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/srovnani/externi-seniorni-vyvojar-vs-full-time-hire",
    proposedPageType: "comparison",
    rationale: "Useful buying-stage page for senior capacity decisions without turning into recruiter content.",
    triggerSignals: ["Capacity-decision queries rise", "Contract-support pages collect hire-vs-contract wording"],
    supportingLinks: ["/cs/spoluprace-na-kontrakt", "/cs/pruvodce/jak-poznat-ze-projekt-potrebuje-externi-seniorni-kapacitu"],
  }),
  candidate({
    id: "new-en-contract-vs-hire",
    candidateType: "new_page",
    locale: "en",
    clusterId: "senior_contract_capacity",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/comparisons/contract-support-vs-full-time-hire",
    proposedPageType: "comparison",
    rationale: "Selective English comparison page for buyer-side staffing decisions.",
    triggerSignals: ["English hire-vs-contract queries appear with project intent", "Contract-support cluster grows"],
    supportingLinks: ["/en/contract-development-support", "/en/guides/how-to-know-when-a-project-needs-senior-contract-support"],
  }),
  candidate({
    id: "new-cs-takeover-audit-guide",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "take_over_app",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/pruvodce/jak-pripravit-takeover-audit-aplikace",
    proposedPageType: "guide",
    rationale: "Natural follow-on guide from takeover and checklist demand.",
    triggerSignals: ["Audit-related takeover queries rise", "Checklist page collects more audit than checklist terms"],
    supportingLinks: ["/cs/sablony/checklist-prevzeti-aplikace", "/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace"],
  }),
  candidate({
    id: "new-en-takeover-audit-guide",
    candidateType: "new_page",
    locale: "en",
    clusterId: "take_over_app",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/guides/how-to-run-an-app-takeover-audit",
    proposedPageType: "guide",
    rationale: "Strong English support page if audit-flavored takeover demand appears.",
    triggerSignals: ["Audit phrasing shows up in English GSC exports", "App takeover checklist outperforms service page for audit terms"],
    supportingLinks: ["/en/templates/app-takeover-checklist", "/en/services/existing-app-takeover"],
  }),
  candidate({
    id: "new-cs-rewrite-decision-guide",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "rewrite_vs_incremental",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/pruvodce/jak-poznat-ze-aplikace-opravdu-potrebuje-rewrite",
    proposedPageType: "guide",
    rationale: "Stronger decision guide around rewrite threshold and practical criteria.",
    triggerSignals: ["Rewrite queries diversify", "Comparison page needs deeper supporting content"],
    supportingLinks: ["/cs/srovnani/rewrite-vs-postupny-rozvoj-aplikace", "/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace"],
  }),
  candidate({
    id: "new-en-rewrite-decision-guide",
    candidateType: "new_page",
    locale: "en",
    clusterId: "rewrite_vs_incremental",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/guides/how-to-decide-if-an-app-needs-a-rewrite",
    proposedPageType: "guide",
    rationale: "Selective English guide for rewrite-threshold searches with commercial fit.",
    triggerSignals: ["English rewrite-threshold queries appear", "Comparison page gathers informational but still buyer-relevant demand"],
    supportingLinks: ["/en/comparisons/rewrite-vs-incremental-app-improvement", "/en/services/existing-app-takeover"],
  }),
  candidate({
    id: "new-cs-automation-discovery-guide",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "automations_and_integrations",
    priority: "HIGH_PRIORITY_SUPPORT",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/pruvodce/jak-pripravit-discovery-pro-automatizaci-a-integrace",
    proposedPageType: "guide",
    rationale: "Good Czech support page between service demand and discovery-template demand.",
    triggerSignals: ["Automation discovery queries rise", "Template and service pages need stronger bridge content"],
    supportingLinks: ["/cs/sablony/discovery-checklist-pro-automatizace", "/cs/sluzby/automatizace-a-integrace"],
  }),
  candidate({
    id: "new-cs-partner-portal-usecase",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "b2b_portal_use_case",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/priklady/partnersky-portal-pro-b2b-firmu",
    proposedPageType: "use_case",
    rationale: "A more partner-facing variant of the existing portal use-case family.",
    triggerSignals: ["Partner portal queries appear", "B2B portal page gathers multiple adjacent terms"],
    supportingLinks: ["/cs/sluzby/vyvoj-webovych-aplikaci-na-miru", "/cs/problemy/potrebujeme-klientsky-portal"],
  }),
  candidate({
    id: "new-cs-service-ops-usecase",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "workflow_app_use_case",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/priklady/operativni-system-pro-servisni-tym",
    proposedPageType: "use_case",
    rationale: "Concrete Czech operations use case adjacent to internal tools and workflow apps.",
    triggerSignals: ["Service operations queries appear", "Workflow/internal-tool pages start sharing support traffic"],
    supportingLinks: ["/cs/sluzby/interni-systemy-na-miru", "/cs/priklady/workflow-aplikace-pro-tym"],
  }),
  candidate({
    id: "new-cs-excel-migration-template",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "internal_tools_development",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/sablony/checklist-migrace-z-excelu-do-interniho-systemu",
    proposedPageType: "tool",
    rationale: "High-utility asset for the internal-tools cluster and spreadsheet replacement demand.",
    triggerSignals: ["Spreadsheet-to-system queries rise", "Scope worksheet needs a more migration-focused sibling"],
    supportingLinks: ["/cs/sluzby/interni-systemy-na-miru", "/cs/sablony/scope-worksheet-pro-interni-system"],
  }),
  candidate({
    id: "new-en-internal-tool-discovery-template",
    candidateType: "new_page",
    locale: "en",
    clusterId: "scope_custom_development",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/en/templates/internal-tool-discovery-brief",
    proposedPageType: "tool",
    rationale: "Selective English utility asset bridging internal-tool scoping and inquiry.",
    triggerSignals: ["Internal-tool brief queries appear", "Guide traffic points to a need for a narrower brief asset"],
    supportingLinks: ["/en/services/internal-tools-development", "/en/templates/internal-tool-scope-worksheet"],
  }),
  candidate({
    id: "new-cs-release-stabilization-template",
    candidateType: "new_page",
    locale: "cs",
    clusterId: "existing_app_takeover",
    priority: "MEDIUM_CLUSTER_EXPANSION",
    targetAction: "CREATE_NEW_PAGE",
    proposedPath: "/cs/sablony/checklist-stabilizace-release-procesu-aplikace",
    proposedPageType: "tool",
    rationale: "Practical takeover/stabilisation asset with clear buyer utility.",
    triggerSignals: ["Release-risk terms appear", "Takeover cluster needs a more operational template asset"],
    supportingLinks: ["/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace", "/cs/pruvodce/jak-prevzit-existujici-aplikaci-bez-rizika"],
  }),
];

export const CONSOLIDATION_CANDIDATES: ContentOpportunityCandidate[] = [
  candidate({
    id: "watch-en-nextjs-comparison",
    candidateType: "consolidate",
    locale: "en",
    clusterId: "nextjs_vs_spa",
    priority: "MERGE_OR_PRUNE",
    targetAction: "NOINDEX_REVIEW",
    currentPath: "/en/comparisons/nextjs-vs-spa-for-business-apps",
    rationale: "Useful only if it stays tightly business-oriented. Broad framework traffic would dilute lead quality.",
    triggerSignals: ["Broad developer impressions with weak commercial clicks", "Low conversion despite clicks", "Query cluster drifts toward generic frontend content"],
    supportingLinks: ["/en/technology/nextjs-for-business-applications", "/en/services/custom-web-application-development"],
  }),
  candidate({
    id: "watch-en-typescript-tech",
    candidateType: "consolidate",
    locale: "en",
    clusterId: "typescript_large_projects",
    priority: "MERGE_OR_PRUNE",
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    currentPath: "/en/technology/typescript-for-large-web-projects",
    rationale: "Potentially too broad unless it keeps clear business-app delivery intent.",
    triggerSignals: ["Generic dev traffic dominates", "Weak internal link progression", "No meaningful commercial leads"],
    supportingLinks: ["/en/technology", "/en/services/custom-web-application-development"],
  }),
  candidate({
    id: "watch-en-postgresql-tech",
    candidateType: "consolidate",
    locale: "en",
    clusterId: "postgresql_internal_tools",
    priority: "MERGE_OR_PRUNE",
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    currentPath: "/en/technology/postgresql-for-internal-tools",
    rationale: "Keep only if it proves buyer-side relevance beyond broad database traffic.",
    triggerSignals: ["Low-intent technical traffic", "No clear assist role for internal-tools conversion", "Overlap with broader technology hub"],
    supportingLinks: ["/en/technology", "/en/services/internal-tools-development"],
  }),
  candidate({
    id: "watch-en-when-custom-dev-guide",
    candidateType: "consolidate",
    locale: "en",
    clusterId: "assess_project_fit",
    priority: "MERGE_OR_PRUNE",
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    currentPath: "/en/guides/when-custom-development-makes-sense",
    rationale: "Useful if it proves intent-specific. Otherwise it overlaps with homepage, service pages, and build-vs-buy content.",
    triggerSignals: ["Low CTR and low conversion", "Query overlap with stronger commercial pages", "No distinct cluster traction"],
    supportingLinks: ["/en/services/custom-web-application-development", "/en/comparisons/custom-web-app-vs-saas-tool"],
  }),
  candidate({
    id: "watch-en-mvp-guide",
    candidateType: "consolidate",
    locale: "en",
    clusterId: "plan_mvp",
    priority: "MERGE_OR_PRUNE",
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    currentPath: "/en/guides/how-to-plan-an-mvp-web-application",
    rationale: "Keep only if the query cluster stays tied to commercial project-scoping intent.",
    triggerSignals: ["Broad startup/PM traffic", "Weak commercial CTA performance", "Overlap with scoping guide and brief template"],
    supportingLinks: ["/en/guides/how-to-scope-a-custom-web-application", "/en/templates/web-app-project-brief-template"],
  }),
  candidate({
    id: "watch-cs-ostrava-location",
    candidateType: "consolidate",
    locale: "cs",
    clusterId: "contract_development_support",
    priority: "MERGE_OR_PRUNE",
    targetAction: "NOINDEX_REVIEW",
    currentPath: "/cs/lokality/ostrava",
    rationale: "Location pages should stay only if they collect local-intent traction without doorway-page behavior.",
    triggerSignals: ["No traction after 90 days", "Thin local-intent support", "Low assist value for commercial pages"],
    supportingLinks: ["/cs/sluzby", "/cs/spoluprace-na-kontrakt"],
  }),
  candidate({
    id: "watch-cs-brno-location",
    candidateType: "consolidate",
    locale: "cs",
    clusterId: "contract_development_support",
    priority: "MERGE_OR_PRUNE",
    targetAction: "NOINDEX_REVIEW",
    currentPath: "/cs/lokality/brno",
    rationale: "Watch for real local signal; otherwise location coverage should remain lean.",
    triggerSignals: ["No meaningful local impressions or clicks", "Low assist to inquiry flow", "No distinct local cluster emerging"],
    supportingLinks: ["/cs/sluzby", "/cs/spoluprace-na-kontrakt"],
  }),
  candidate({
    id: "watch-cs-api-vs-automation-template-overlap",
    candidateType: "consolidate",
    locale: "cs",
    clusterId: "api_integrations",
    priority: "MERGE_OR_PRUNE",
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    currentPath: "/cs/sablony/checklist-api-integrace",
    rationale: "Possible overlap with the automation discovery checklist if both attract the same cluster without distinct intent.",
    triggerSignals: ["Same query cluster appears on both assets", "One asset clearly dominates", "Weak differentiation in clicks and internal progression"],
    supportingLinks: ["/cs/sablony/discovery-checklist-pro-automatizace", "/cs/sluzby/automatizace-a-integrace"],
  }),
  candidate({
    id: "watch-en-api-vs-automation-template-overlap",
    candidateType: "consolidate",
    locale: "en",
    clusterId: "api_integrations",
    priority: "MERGE_OR_PRUNE",
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    currentPath: "/en/templates/api-integration-checklist",
    rationale: "Template overlap should be reduced if one English asset dominates the integration-discovery cluster.",
    triggerSignals: ["Identical English query family for two assets", "No clear difference in click-through or commercial progression"],
    supportingLinks: ["/en/templates/automation-discovery-checklist", "/en/services/automations-and-integrations"],
  }),
  candidate({
    id: "watch-en-management-dashboard-usecase",
    candidateType: "consolidate",
    locale: "en",
    clusterId: "reporting_dashboard_use_case",
    priority: "MERGE_OR_PRUNE",
    targetAction: "MERGE_INTO_HUB",
    currentPath: "/en/use-cases/management-dashboard",
    rationale: "Keep only if it builds a real business-intent cluster rather than broad BI/reporting traffic.",
    triggerSignals: ["Broad dashboard traffic with weak leads", "Low query distinctiveness compared to hub and internal-tools pages"],
    supportingLinks: ["/en/use-cases", "/en/services/internal-tools-development"],
  }),
];

export const INITIAL_AUDIT_NOTES: ContentAuditNote[] = [
  {
    pagePath: "/cs",
    locale: "cs",
    contentStatus: "core",
    optimizationPriority: "HIGH_PRIORITY_MONEY",
    reviewReason: "MANUAL_BASELINE",
    queryCluster: "custom_web_application_development",
    expansionCandidate: false,
    pruneCandidate: false,
    targetAction: "REWRITE_EXISTING",
    notes: ["Primary Czech homepage. Revisit every 30 days against GSC homepage/service-entry patterns."],
  },
  {
    pagePath: "/cs/sluzby/prevzeti-a-rozvoj-existujici-aplikace",
    locale: "cs",
    contentStatus: "core",
    optimizationPriority: "HIGH_PRIORITY_MONEY",
    reviewReason: "MANUAL_BASELINE",
    queryCluster: "existing_app_takeover",
    expansionCandidate: true,
    pruneCandidate: false,
    targetAction: "REWRITE_EXISTING",
    notes: ["Treat as one of the main revenue pages for takeover, rescue, and stabilisation demand."],
  },
  {
    pagePath: "/cs/pruvodce/jak-zadat-vyvoj-webove-aplikace",
    locale: "cs",
    contentStatus: "watchlist",
    optimizationPriority: "HIGH_PRIORITY_SUPPORT",
    reviewReason: "MANUAL_BASELINE",
    queryCluster: "scope_custom_development",
    expansionCandidate: true,
    pruneCandidate: false,
    targetAction: "EXPAND_EXISTING",
    notes: ["Guide likely to become a winner if scope/brief/MVP queries start clustering."],
  },
  {
    pagePath: "/en/technology/typescript-for-large-web-projects",
    locale: "en",
    contentStatus: "consolidation_review",
    optimizationPriority: "MERGE_OR_PRUNE",
    reviewReason: "LOW_VALUE_BROAD_TRAFFIC",
    queryCluster: "typescript_large_projects",
    expansionCandidate: false,
    pruneCandidate: true,
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    notes: ["Keep only if it proves business-app decision value rather than generic dev traffic."],
  },
  {
    pagePath: "/cs/sablony/checklist-api-integrace",
    locale: "cs",
    contentStatus: "watchlist",
    optimizationPriority: "MERGE_OR_PRUNE",
    reviewReason: "OVERLAPPING_CONTENT",
    queryCluster: "api_integrations",
    expansionCandidate: false,
    pruneCandidate: true,
    targetAction: "MERGE_WITH_STRONGER_PAGE",
    notes: ["Review overlap with the automation discovery checklist after enough GSC signal exists."],
  },
];

export function getCandidatesByType(type: ContentOpportunityCandidate["candidateType"]) {
  const all = [
    ...REWRITE_CANDIDATES,
    ...EXPANSION_CANDIDATES,
    ...NEW_PAGE_CANDIDATES,
    ...CONSOLIDATION_CANDIDATES,
  ];

  return all.filter((candidateEntry) => candidateEntry.candidateType === type);
}
