// Generated content: additional high-intent use-case pages. Safe to edit manually.

import { buildInquiryHref, definePage } from "@/content/builders";
import type { ContentPage, FAQItem, Locale } from "@/content/types";

type UseCaseSeed = {
  translationKey: string;
  locale: Locale;
  slug: string;
  title: string;
  h1: string;
  description: string;
  primaryQuery: string;
  heroTitle: string;
  heroSubtitle: string;
  intro: string[];
  scenarios: string[];
  includes: string[];
  outcomes: string[];
  faq: FAQItem[];
  related: string[];
  fitFor: string[];
  fitNot: string[];
};

function defineGrowthUseCasePage(seed: UseCaseSeed): ContentPage {
  const isCs = seed.locale === "cs";

  return definePage({
    translationKey: seed.translationKey,
    stage: 2,
    locale: seed.locale,
    pageType: "use_case",
    slug: seed.slug,
    segments: [isCs ? "priklady" : "use-cases", seed.slug],
    title: seed.title,
    h1: seed.h1,
    description: seed.description,
    primaryQuery: seed.primaryQuery,
    intent: "commercial",
    hero: {
      eyebrow: isCs ? "Příklad řešení" : "Use case",
      title: seed.heroTitle,
      subtitle: seed.heroSubtitle,
      primaryCta: {
        label: isCs ? "Popsat podobný projekt" : "Discuss a similar project",
        href: buildInquiryHref(seed.locale),
      },
    },
    intro: seed.intro,
    sections: [
      {
        title: isCs ? "Kdy tento typ řešení dává smysl" : "When this type of solution makes sense",
        body: [
          isCs
            ? "Use case není šablona pro každou firmu. Je to reprezentativní model situace, kde dává podobný systém jasný obchodní a provozní smysl."
            : "This is not a universal template. It is a representative model of situations where a similar system makes clear commercial and operational sense.",
        ],
        bullets: seed.scenarios,
      },
      {
        title: isCs ? "Co bývá součástí řešení" : "What the solution usually includes",
        body: [
          isCs
            ? "Konkrétní scope se liší podle firmy, ale opakují se podobné role, workflow, datové vazby a místa, kde je potřeba jasná odpovědnost."
            : "The exact scope varies by company, but similar patterns repeat around roles, workflow, data boundaries, and ownership.",
        ],
        bullets: seed.includes,
      },
      {
        title: isCs ? "Jaký výsledek by měl systém přinést" : "What the system should improve",
        body: [
          isCs
            ? "Smyslem není jen nahradit starý nástroj novým. Důležité je zjednodušit práci lidí, zpřehlednit stav a snížit zbytečné ruční zásahy."
            : "The point is not merely replacing one tool with another. The important part is reducing friction, clarifying state, and lowering avoidable manual work.",
        ],
        bullets: seed.outcomes,
      },
    ],
    faq: seed.faq,
    related: seed.related,
    fit: { for: seed.fitFor, notFor: seed.fitNot },
    cta: isCs
      ? {
          label: "Probrat podobné zadání",
          href: "/cs/popsat-projekt",
          note: "Stačí krátce popsat proces, role a co dnes nefunguje. Navrhnu rozumný další krok.",
        }
      : {
          label: "Explore the project fit",
          href: "/en/discuss-your-project",
          note: "A short summary of the workflow, users, and current friction is enough to assess the fit.",
        },
    seo: { title: seed.title, description: seed.description },
    schema: { includeFaq: true },
    indexable: true,
  });
}

export const growthUseCasePages: ContentPage[] = [
  defineGrowthUseCasePage({
    translationKey: "use-case-b2b-partner-portal",
    locale: "cs",
    slug: "partnersky-portal-pro-b2b-firmu",
    title: "Partnerský portál pro B2B firmu | Bc. Ondřej Halata (halatao.cz)",
    h1: "Partnerský portál pro B2B firmu a sdílený provozní přehled",
    description: "Příklad partnerského portálu pro B2B firmu, která potřebuje sjednotit dokumenty, požadavky, stav spolupráce a samoobslužné kroky distributorů, dealerů nebo partnerů.",
    primaryQuery: "partnersky portal pro B2B firmu",
    heroTitle: "Jedno místo pro partnery místo e-mailových vláken a ručního dohledávání",
    heroSubtitle: "Vhodné tam, kde partneři opakovaně pracují s dokumenty, požadavky, stavem zakázek nebo dalšími kroky napojenými na interní proces firmy.",
    intro: [
      "Partnerský portál je silný use case tam, kde firma neřeší jen jednorázový klientský vstup, ale dlouhodobou spolupráci s distributory, obchodními partnery nebo servisní sítí.",
      "První verze by obvykle měla začínat několika scénáři s nejvyšším dopadem na vztah s partnerem a interní operativu, ne pokusem digitalizovat celou spolupráci najednou.",
    ],
    scenarios: [
      "partneři potřebují průběžně vidět stav požadavků, objednávek nebo servisních případů",
      "dokumenty, ceníky nebo podklady se sdílejí ručně a nepřehledně",
      "firma chce partnerům nabídnout samoobslužné kroky bez zbytečné interní asistence",
      "obchodní nebo operativní tým ztrácí čas opakovanou podporou partnerů",
    ],
    includes: [
      "partnerské účty, role a přístupové úrovně",
      "stav spolupráce, požadavků nebo zakázek v jednom rozhraní",
      "správu dokumentů, notifikace a navazující akce",
      "napojení na interní systém, CRM nebo backoffice workflow",
    ],
    outcomes: [
      "méně ruční partnerské podpory a dohledávání",
      "lepší dostupnost informací pro partnera",
      "větší důvěra v servisní a obchodní proces",
      "silnější základ pro další digitální služby pro partnery",
    ],
    faq: [
      { question: "Je partnerský portál něco jiného než klientský portál?", answer: "Často ano. Partnerská spolupráce mívá jiné role, oprávnění a dlouhodobější provozní vazbu na interní proces firmy." },
      { question: "Musí portál od začátku řešit všechny scénáře spolupráce?", answer: "Nemusí. Lepší je začít několika nejčastějšími interakcemi, které odlehčí podporu a zpřehlední provoz." },
      { question: "Lze portál napojit na stávající interní systémy?", answer: "Ano. Právě vazba na interní data a workflow je pro podobný projekt klíčová." },
    ],
    related: ["service-custom-web-app-development", "use-case-b2b-client-portal", "problem-client-portal", "inquiry"],
    fitFor: ["B2B firmy s opakovanou spoluprací s partnery", "týmy, které chtějí snížit servisní overhead kolem partnerů", "situace, kde má portál jasnou vazbu na interní proces a data"],
    fitNot: ["jednoduchá prezentační sekce pro partnery bez workflow", "portál bez návaznosti na interní systém", "projekty bez ownera partnerského procesu"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-service-team-ops-system",
    locale: "cs",
    slug: "operativni-system-pro-servisni-tym",
    title: "Operativní systém pro servisní tým | Bc. Ondřej Halata (halatao.cz)",
    h1: "Operativní systém pro servisní tým místo tabulek a ruční koordinace",
    description: "Příklad operativního systému pro servisní tým, který potřebuje řídit požadavky, stavy, termíny a odpovědnost bez roztříštěných tabulek a chatu.",
    primaryQuery: "operativni system pro servisni tym",
    heroTitle: "Jeden systém pro servisní operativu místo ručního přeposílání a dohledávání",
    heroSubtitle: "Vhodné tam, kde servisní tým řeší opakované požadavky, předává práci mezi rolemi a potřebuje lepší dohled nad stavem a výjimkami.",
    intro: [
      "Operativní systém pro servisní tým dává smysl ve chvíli, kdy už nestačí tabulka, sdílený inbox a ruční předávání informací mezi lidmi.",
      "Nejdůležitější není nahradit jeden formulář novou obrazovkou. Důležité je zkrátit průchod procesem, zpřehlednit odpovědnost a omezit místa, kde se servisní práce zasekává.",
    ],
    scenarios: [
      "servisní požadavky se předávají mezi více rolemi a odděleními",
      "není jasné, kde se případ zastavil a kdo má další krok",
      "termíny, výjimky a eskalace se hlídají ručně",
      "tým potřebuje napojení na další interní nebo externí systémy",
    ],
    includes: [
      "pracovní frontu, stavy a pravidla předávání mezi rolemi",
      "detail případu, historii, termíny a auditní stopu",
      "notifikace, eskalace a dohled nad výjimkami",
      "napojení na CRM, ERP, servisní evidenci nebo skladový tok",
    ],
    outcomes: [
      "vyšší průchodnost servisního procesu",
      "nižší závislost na ruční koordinaci a dohledávání",
      "lepší přehled o výjimkách, SLA a zpožděních",
      "pevnější základ pro další automatizaci servisního workflow",
    ],
    faq: [
      { question: "Je to vhodné i pro menší servisní tým?", answer: "Ano, pokud se stejný proces opakuje dost často na to, aby ruční koordinace začala brzdit kapacitu nebo kvalitu obsluhy." },
      { question: "Musí systém od začátku pokrýt všechny typy případů?", answer: "Nemusí. Často dává smysl začít jedním typem workflow nebo jednou provozně nejbolestivější oblastí." },
      { question: "Lze ho propojit s dalšími firemními nástroji?", answer: "Ano. U servisní operativy bývá návaznost na další systémy často důležitá pro rychlost i spolehlivost procesu." },
    ],
    related: ["service-internal-tools-development", "service-ai-automation-and-integrations", "use-case-ai-intake-triage", "use-case-workflow-automation-tools", "problem-replace-spreadsheets-in-process", "inquiry"],
    fitFor: ["servisní nebo provozní týmy s opakovaným workflow", "firmy, které chtějí zkrátit ruční koordinaci a zlepšit dohled", "procesy s více rolemi, termíny a výjimkami"],
    fitNot: ["jednoduchá evidence bez návazného workflow", "projekty bez ownera servisního procesu", "situace, kde jde jen o kosmetický redesign bez provozní změny"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-b2b-client-portal",
    locale: "cs",
    slug: "b2b-klientsky-portal",
    title: "B2B klientský portál na míru | Bc. Ondřej Halata (halatao.cz)",
    h1: "B2B klientský portál pro zakázky, dokumenty a samoobsluhu",
    description: "Příklad B2B klientského portálu na míru pro firmy, které chtějí sjednotit komunikaci, dokumenty, stavy zakázek a samoobslužné kroky partnerů nebo klientů.",
    primaryQuery: "B2B klientský portál na míru",
    heroTitle: "Jeden portál místo e-mailových vláken a ručního posílání informací",
    heroSubtitle: "Vhodné pro B2B služby a provozy, kde klienti opakovaně řeší stav zakázky, dokumenty, požadavky nebo další kroky.",
    intro: [
      "B2B klientský portál dává smysl ve chvíli, kdy firma obsluhuje opakované klientské interakce a nechce je dál držet v e-mailech, sdílených složkách a ruční podpoře.",
      "Silná první verze obvykle nezačíná širokým seznamem funkcí, ale několika klíčovými scénáři s největším dopadem na klientský servis i interní operativu.",
    ],
    scenarios: [
      "klienti opakovaně žádají stav zakázky nebo služby",
      "dokumenty a přílohy se posílají ručně",
      "firma potřebuje bezpečnější samoobslužné úkony pro klienta",
      "obchodní nebo operativní tým tráví moc času podporou opakujících se dotazů",
    ],
    includes: [
      "uživatelské účty, role a přístupy",
      "přehled stavu, historie a dalších kroků",
      "správu dokumentů, notifikace a akce",
      "napojení na interní systém, CRM nebo fakturační tok",
    ],
    outcomes: [
      "méně ruční klientské podpory",
      "lepší dostupnost informací pro klienta",
      "důvěryhodnější servisní proces",
      "pevnější základ pro další digitální služby",
    ],
    faq: [
      { question: "Musí být portál rozsáhlý od začátku?", answer: "Nemusí. U B2B portálů bývá nejlepší začít několika nejčastějšími klientskými scénáři." },
      { question: "Lze portál napojit na stávající interní systém?", answer: "Ano. Právě návaznost na interní data a workflow je pro podobný projekt klíčová." },
      { question: "Je portál vhodný i bez interní administrace?", answer: "Většinou ne. Dobře fungující portál bývá navázaný na rozumné backoffice rozhraní." },
    ],
    related: ["service-custom-web-app-development", "problem-client-portal", "use-case-b2b-partner-portal", "comparison-custom-vs-saas", "inquiry"],
    fitFor: ["B2B firmy s opakovanou klientskou komunikací", "služby a provozy s dokumenty, stavy a samoobsluhou", "týmy, které chtějí snížit support overhead"],
    fitNot: ["jednorázová prezentační microsite", "portál bez návaznosti na interní data", "projekty bez jasného provozního use case"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-internal-approval-system",
    locale: "cs",
    slug: "interni-schvalovaci-system",
    title: "Interní schvalovací systém na míru | Bc. Ondřej Halata (halatao.cz)",
    h1: "Interní schvalovací systém pro více rolí a jasná pravidla",
    description: "Příklad interního schvalovacího systému na míru pro firmy, kde se žádosti, výjimky nebo objednávky schvalují přes e-maily, tabulky a ruční dohledávání stavu.",
    primaryQuery: "interní schvalovací systém",
    heroTitle: "Schvalování, které už nemusí stát na ručním hlídání a přeposílání",
    heroSubtitle: "Pro firmy, kde schvalovací proces ovlivňuje finance, provoz nebo odpovědnost mezi týmy.",
    intro: [
      "Schvalovací systém je typický use case tam, kde je potřeba hlídat role, pravidla, výjimky a auditní stopu a současný stav stojí na e-mailech a manuálních připomínkách.",
      "Dobře navržené řešení má zkrátit průchod procesem, zpřehlednit odpovědnost a zlepšit kontrolu nad tím, kde se schválení zaseklo.",
    ],
    scenarios: [
      "schvalování objednávek, výdajů nebo žádostí",
      "více úrovní oprávnění a výjimek",
      "nutnost auditní stopy a dohledatelnosti",
      "ruční připomínání a eskalace mezi týmy",
    ],
    includes: [
      "workflow stavy a schvalovací pravidla",
      "role, oprávnění a historie kroků",
      "notifikace, připomínky a eskalace",
      "napojení na ERP, účetnictví nebo interní agendu",
    ],
    outcomes: [
      "rychlejší průchod schvalovacím procesem",
      "menší množství ruční koordinace",
      "lepší auditní stopa a odpovědnost",
      "nižší provozní chybovost",
    ],
    faq: [
      { question: "Lze zachovat ruční schválení tam, kde je potřeba?", answer: "Ano. Smyslem není vše bezhlavě automatizovat, ale oddělit pravidla od výjimek." },
      { question: "Je to vhodné i pro menší firmu?", answer: "Ano, pokud schvalování reálně zpomaluje provoz nebo vytváří finanční a procesní riziko." },
      { question: "Dá se systém nasadit po částech?", answer: "Ano. Často dává smysl začít jedním typem žádosti nebo jedním oddělením." },
    ],
    related: ["service-internal-tools-development", "service-automations-and-integrations", "problem-internal-tool", "inquiry"],
    fitFor: ["firmy s více rolemi a schvalovací logikou", "procesy s auditní stopou a výjimkami", "týmy, které chtějí snížit ruční dohled nad stavem"],
    fitNot: ["jednoduchý proces bez rolí a pravidel", "firma bez ownera schvalovacího workflow", "nákup hotového formuláře bez integrací"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-management-dashboard",
    locale: "cs",
    slug: "dashboard-pro-management",
    title: "Dashboard pro management na míru | Bc. Ondřej Halata (halatao.cz)",
    h1: "Dashboard pro management nad daty z více systémů",
    description: "Příklad management dashboardu na míru pro firmy, které potřebují spojit data z více zdrojů a zlepšit rozhodování bez ručně skládaných reportů.",
    primaryQuery: "dashboard pro management",
    heroTitle: "Přehled pro vedení, který nestojí na ručně lepených exportech",
    heroSubtitle: "Vhodné tam, kde management potřebuje rychle vidět stav firmy, výjimky a trendy nad několika systémy.",
    intro: [
      "Management dashboard dává smysl ve chvíli, kdy se zásadní rozhodnutí opírají o neaktuální exporty, ručně spojovaná čísla nebo reporting závislý na konkrétních lidech.",
      "Smyslem dashboardu není jen hezký graf. Důležité je, aby čísla měla jasný původ, dávala smysl v provozním kontextu a šla bezpečně interpretovat.",
    ],
    scenarios: [
      "vedení skládá reporty z více systémů",
      "čísla se mezi nástroji rozcházejí",
      "chybí včasná viditelnost do výjimek a problémů",
      "operativa a management pracují s jinou verzí reality",
    ],
    includes: [
      "sjednocení klíčových datových zdrojů",
      "role a pohledy podle typu uživatele",
      "přehled KPI, trendů a varování",
      "napojení na interní aplikaci nebo BI vrstvu",
    ],
    outcomes: [
      "rychlejší a jistější rozhodování",
      "méně ručního reportingu",
      "lepší důvěra v data",
      "včasnější reakce na provozní výjimky",
    ],
    faq: [
      { question: "Není lepší koupit hotové BI?", answer: "Někdy ano. Pokud ale dashboard potřebuje specifické role, workflow nebo vazbu na vlastní aplikaci, dává custom řešení větší smysl." },
      { question: "Musí se nejdřív vyčistit data?", answer: "Aspoň v klíčových oblastech ano. Jinak dashboard jen vizualizuje stávající chaos." },
      { question: "Je dashboard jen pro vedení?", answer: "Ne vždy. Často je praktický i pro operativní role, které potřebují včas vidět odchylky a výjimky." },
    ],
    related: ["service-internal-tools-development", "use-case-reporting-dashboard", "service-automations-and-integrations", "inquiry"],
    fitFor: ["firmy s daty rozptýlenými v několika systémech", "management, který dnes spoléhá na ruční reporting", "týmy, které potřebují jednotnější pohled na stav firmy"],
    fitNot: ["dashboard bez důvěryhodného zdroje dat", "jednorázový reporting bez provozního dopadu", "projekty bez ownera na straně businessu"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-workflow-app-for-teams",
    locale: "cs",
    slug: "workflow-aplikace-pro-tym",
    title: "Workflow aplikace pro tým | Bc. Ondřej Halata (halatao.cz)",
    h1: "Workflow aplikace pro tým a opakované provozní procesy",
    description: "Příklad workflow aplikace pro tým, který potřebuje řídit opakovaný proces, role, stavy a návazné kroky bez ruční koordinace přes tabulky a chaty.",
    primaryQuery: "workflow aplikace pro tým",
    heroTitle: "Jeden pracovní tok místo přeposílání, tabulek a ručního dohledávání",
    heroSubtitle: "Pro týmy, kde se stejný proces opakuje stále dokola a dnes je příliš závislý na ruční koordinaci.",
    intro: [
      "Workflow aplikace bývá správný typ řešení tam, kde proces není jen evidence dat, ale sled navazujících kroků mezi více rolemi, výjimkami a termíny.",
      "Dobře navržená workflow aplikace pomáhá zpřehlednit odpovědnost, zkrátit průchod procesem a omezit počet míst, kde se práce ztrácí nebo zasekává.",
    ],
    scenarios: [
      "opakované procesy s více rolemi a stavy",
      "ruční předávání práce mezi lidmi nebo odděleními",
      "nízká dohledatelnost, kde se proces zasekl",
      "potřeba napojení na další interní nebo externí systémy",
    ],
    includes: [
      "workflow stavy, pravidla a oprávnění",
      "detail položky, historie a auditní stopu",
      "notifikace, termíny a výjimky",
      "napojení na CRM, ERP nebo další interní nástroje",
    ],
    outcomes: [
      "vyšší průchodnost procesu",
      "nižší závislost na ruční koordinaci",
      "lepší dohled nad výjimkami a zpožděním",
      "pevnější základ pro další automatizaci",
    ],
    faq: [
      { question: "Je workflow aplikace totéž co interní admin?", answer: "Ne úplně. Workflow aplikace bývá více postavená kolem stavů, pravidel a průchodu procesem." },
      { question: "Dá se spustit jen pro jednu část procesu?", answer: "Ano. To bývá často nejrozumnější první krok." },
      { question: "Lze kombinovat workflow aplikaci a automatizace?", answer: "Ano. V praxi se tyto dvě vrstvy často doplňují." },
    ],
    related: ["service-internal-tools-development", "service-automations-and-integrations", "service-ai-automation-and-integrations", "use-case-workflow-automation-tools", "inquiry"],
    fitFor: ["týmy s opakovaným multi-step procesem", "provozy s více rolemi a výjimkami", "firmy, které chtějí zkrátit průchod a zlepšit dohled"],
    fitNot: ["jednoduchý seznam úkolů bez workflow", "proces bez jasných stavů a odpovědností", "projekty bez ochoty popsat skutečný provoz"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-b2b-client-portal",
    locale: "en",
    slug: "b2b-client-portal",
    title: "B2B client portal development | Bc. Ondřej Halata (halatao.cz)",
    h1: "B2B client portal for orders, documents, and self-service",
    description: "A B2B client portal use case for companies that want one place for business-customer communication, documents, order status, and self-service actions.",
    primaryQuery: "B2B client portal development",
    heroTitle: "One portal instead of email threads and manual updates",
    heroSubtitle: "Useful for B2B services and operations where business customers repeatedly need status updates, documents, requests, or guided next steps.",
    intro: [
      "A B2B client portal makes sense when the company keeps repeating the same communication and support work with business customers around service delivery, documents, or account actions.",
      "The strongest first version usually focuses on the few client scenarios with the highest operational impact rather than trying to digitise everything at once or drifting into partner-collaboration use cases.",
    ],
    scenarios: [
      "clients repeatedly ask for status updates",
      "documents and attachments are shared manually",
      "self-service actions would reduce support load",
      "internal teams spend too much time answering the same questions",
    ],
    includes: [
      "accounts, roles, and access control",
      "status views, history, and next-step guidance",
      "documents, notifications, and actions",
      "integration with internal systems, CRM, or billing flow",
    ],
    outcomes: [
      "lower manual support overhead",
      "better client-side visibility",
      "more credible service delivery",
      "a stronger base for future digital services",
    ],
    faq: [
      { question: "Does the portal need to be large from the start?", answer: "No. A narrower first version focused on the most repeated client interactions is often the better move." },
      { question: "Can it connect to an existing internal system?", answer: "Yes. In most cases the portal is only valuable if it is grounded in internal workflow and data." },
      { question: "Do we also need an admin side?", answer: "Usually yes. A useful portal normally depends on a sensible internal operating layer as well." },
    ],
    related: ["service-custom-web-app-development", "problem-client-portal", "use-case-b2b-partner-portal", "comparison-custom-vs-saas", "inquiry"],
    fitFor: ["B2B companies with repeated client communication", "services with document and status handling", "teams that want to reduce support cost through self-service"],
    fitNot: ["one-off brochure sites", "a portal with no internal data connection", "projects with no operational use case behind them"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-internal-approval-system",
    locale: "en",
    slug: "internal-approval-system",
    title: "Internal approval system | Bc. Ondřej Halata (halatao.cz)",
    h1: "Internal approval system for multi-step business processes",
    description: "An internal approval system use case for companies where requests, purchases, exceptions, or approvals still move through email, spreadsheets, and manual chasing.",
    primaryQuery: "internal approval system",
    heroTitle: "Approvals that no longer depend on manual chasing and forwarding",
    heroSubtitle: "Useful when approval flow affects cost, compliance, or operational speed across several people and teams.",
    intro: [
      "Approval systems are a strong fit when the process depends on roles, rules, exceptions, and traceability, but the current reality lives in inboxes and manual reminders.",
      "A good implementation should shorten cycle time, clarify ownership, and make it obvious where the process is blocked and why.",
    ],
    scenarios: [
      "approval of purchases, expenses, or requests",
      "several approval layers and exception rules",
      "need for traceability and audit history",
      "manual reminders and escalation across teams",
    ],
    includes: [
      "workflow states and approval logic",
      "roles, permissions, and action history",
      "notifications, reminders, and escalation",
      "integration with ERP, finance, or internal operations systems",
    ],
    outcomes: [
      "faster approval throughput",
      "less manual coordination",
      "clearer accountability and audit trail",
      "lower operational error rate",
    ],
    faq: [
      { question: "Can some approvals stay manual?", answer: "Yes. The point is not blind automation but separating the rules from the exceptions." },
      { question: "Is this relevant for a smaller company too?", answer: "Yes, if approval flow is already creating financial or operational drag." },
      { question: "Can it be rolled out in stages?", answer: "Yes. Starting with one request type or one team is often the safer path." },
    ],
    related: ["service-internal-tools-development", "service-automations-and-integrations", "problem-internal-tool", "inquiry"],
    fitFor: ["companies with repeated approval logic", "multi-role workflows with audit needs", "teams trying to reduce manual follow-up and delays"],
    fitNot: ["simple single-step approval flows", "buyers with no process owner", "form tools with no integration or rules"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-management-dashboard",
    locale: "en",
    slug: "management-dashboard",
    title: "Management dashboard development | Bc. Ondřej Halata (halatao.cz)",
    h1: "Management dashboard across several business systems",
    description: "A management dashboard use case for companies that need a more reliable operational and leadership view across several systems.",
    primaryQuery: "management dashboard development",
    heroTitle: "A leadership dashboard that does not rely on manually stitched exports",
    heroSubtitle: "Useful when management decisions depend on fragmented reports, conflicting numbers, or late visibility into operational issues.",
    intro: [
      "A management dashboard is valuable when important decisions rely on reports assembled by hand or on data that is always one step behind reality.",
      "The value is not the chart itself. It is confidence in where the numbers come from and whether they reflect the live business well enough to act on.",
    ],
    scenarios: [
      "leadership reporting assembled from several tools",
      "conflicting numbers across systems",
      "poor visibility into exceptions or delays",
      "operations and management using different versions of reality",
    ],
    includes: [
      "unification of the key data sources",
      "role-based views and access",
      "KPIs, trends, and alerts",
      "integration with internal tooling or BI layers",
    ],
    outcomes: [
      "faster and more confident decisions",
      "less manual reporting work",
      "higher trust in operational data",
      "earlier visibility into issues",
    ],
    faq: [
      { question: "Would off-the-shelf BI be better?", answer: "Sometimes. But when the dashboard needs product-specific roles, workflow context, or close integration with your internal system, custom work can be the better fit." },
      { question: "Do we need cleaner data first?", answer: "At least in the critical areas, yes. Otherwise the dashboard simply visualises the existing confusion." },
      { question: "Is this only for leadership?", answer: "Not always. Operational teams often benefit just as much from timely visibility and exception monitoring." },
    ],
    related: ["service-internal-tools-development", "use-case-reporting-dashboard", "service-automations-and-integrations", "inquiry"],
    fitFor: ["companies with several fragmented data sources", "leadership teams relying on manual reporting", "teams that need a more shared view of business state"],
    fitNot: ["dashboards with no reliable data source", "one-off reporting with no operational value", "projects with no business owner for the numbers"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-workflow-app-for-teams",
    locale: "en",
    slug: "workflow-app-for-teams",
    title: "Workflow app for teams | Bc. Ondřej Halata (halatao.cz)",
    h1: "Workflow app for teams running repeatable operations",
    description: "A workflow app use case for teams that need to manage repeatable processes, states, and responsibilities without relying on spreadsheet and chat coordination.",
    primaryQuery: "workflow app for teams",
    heroTitle: "One operating flow instead of forwarding work by hand",
    heroSubtitle: "A strong fit where the same process repeats across several people, states, deadlines, and exception paths.",
    intro: [
      "A workflow app is often the right shape when the process is more than data entry. It is a chain of steps, responsibilities, exceptions, and deadlines that needs clearer control.",
      "The right result is a more reliable process with less manual chasing, better visibility, and cleaner handoffs across the team.",
    ],
    scenarios: [
      "repeatable processes with several roles and states",
      "manual handover between people or departments",
      "low visibility into where work is stuck",
      "need to connect the process to other internal or external systems",
    ],
    includes: [
      "workflow states, rules, and permissions",
      "item detail, history, and audit trail",
      "notifications, deadlines, and exceptions",
      "integration with CRM, ERP, or internal tools",
    ],
    outcomes: [
      "higher process throughput",
      "less manual coordination dependency",
      "better visibility into delays and exceptions",
      "stronger base for further automation",
    ],
    faq: [
      { question: "Is a workflow app the same as an internal admin system?", answer: "Not exactly. A workflow app is more explicitly built around states, handoffs, and process flow." },
      { question: "Can this start with only one part of the process?", answer: "Yes. That is often the most sensible first step." },
      { question: "Can it combine with automation work?", answer: "Yes. In practice the application and automation layers often reinforce each other." },
    ],
    related: ["service-internal-tools-development", "service-automations-and-integrations", "service-ai-automation-and-integrations", "use-case-workflow-automation-tools", "inquiry"],
    fitFor: ["teams with repeatable multi-step operations", "business processes with several roles and exception paths", "buyers trying to shorten cycle time and improve control"],
    fitNot: ["simple task lists with no workflow logic", "processes with no clear states or ownership", "projects with no willingness to describe the real operating model"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-b2b-partner-portal",
    locale: "en",
    slug: "partner-portal-for-b2b-company",
    title: "Partner portal for a B2B company | Bc. Ondrej Halata (halatao.cz)",
    h1: "Partner portal for a B2B company and shared operational visibility",
    description: "A partner-portal use case for B2B companies that need one place for documents, requests, collaboration status, and self-service actions for distributors, resellers, or business partners.",
    primaryQuery: "partner portal for b2b company",
    heroTitle: "One place for partners instead of email threads and manual follow-up",
    heroSubtitle: "Useful when partners repeatedly need documents, request status, order context, or guided next steps connected to the company's internal process.",
    intro: [
      "A partner portal is a strong use case where the company is not just serving one-off client requests but supporting ongoing work with distributors, commercial partners, or a partner network.",
      "The strongest first version usually starts with a few scenarios that have the biggest impact on partner experience and internal operations rather than trying to digitise the whole relationship at once.",
    ],
    scenarios: [
      "partners repeatedly need status visibility for requests, orders, or service cases",
      "documents, pricing, or support materials are still shared manually",
      "the company wants self-service steps for partners without extra internal overhead",
      "commercial or operations teams spend too much time on repetitive partner support",
    ],
    includes: [
      "partner accounts, roles, and access boundaries",
      "status visibility for requests, collaboration, or orders",
      "document handling, notifications, and next-step actions",
      "integration with internal systems, CRM, or back-office workflow",
    ],
    outcomes: [
      "less manual partner support and follow-up",
      "better information access for partners",
      "greater trust in the operational and service process",
      "a stronger base for future digital partner services",
    ],
    faq: [
      { question: "Is a partner portal different from a client portal?", answer: "Often yes. Partner collaboration usually has different roles, permissions, and a longer operational relationship with the internal process." },
      { question: "Does the portal need to cover every partner scenario from day one?", answer: "No. It is usually better to start with the few interactions that reduce support load and improve clarity fastest." },
      { question: "Can the portal connect to existing internal systems?", answer: "Yes. The link to internal data and workflow is usually what makes the portal genuinely useful." },
    ],
    related: ["service-custom-web-app-development", "use-case-b2b-client-portal", "problem-client-portal", "inquiry"],
    fitFor: ["B2B companies working with recurring partner interactions", "teams trying to reduce support overhead around partners", "situations where the portal clearly connects to internal process and data"],
    fitNot: ["simple presentation-only partner areas", "portals with no connection to internal systems", "projects with no owner for the partner workflow"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-service-team-ops-system",
    locale: "en",
    slug: "operations-system-for-a-service-team",
    title: "Operations system for a service team | Bc. Ondrej Halata (halatao.cz)",
    h1: "Operations system for a service team instead of spreadsheets and manual coordination",
    description: "An operations-system use case for service teams that need to manage requests, states, deadlines, and ownership without fragmented spreadsheets and chat messages.",
    primaryQuery: "operations system for a service team",
    heroTitle: "One system for service operations instead of constant forwarding and follow-up",
    heroSubtitle: "Useful when a service team handles recurring requests, hands work across several roles, and needs clearer visibility into state and exceptions.",
    intro: [
      "An operations system for a service team makes sense once a spreadsheet, shared inbox, and manual handoff model stop being reliable enough.",
      "The goal is not replacing one form with another screen. The goal is shortening the flow, clarifying ownership, and reducing the points where service work gets stuck.",
    ],
    scenarios: [
      "service requests move across several roles or departments",
      "nobody can clearly see where a case is blocked or who owns the next step",
      "deadlines, escalations, and exceptions are still tracked manually",
      "the team needs integration with other internal or external systems",
    ],
    includes: [
      "work queues, states, and handoff rules across roles",
      "case detail, history, deadlines, and audit trail",
      "notifications, escalations, and exception visibility",
      "integration with CRM, ERP, service records, or inventory flow",
    ],
    outcomes: [
      "higher service-process throughput",
      "less dependence on manual coordination and follow-up",
      "better visibility into SLA risk, delays, and exceptions",
      "a stronger base for further service-workflow automation",
    ],
    faq: [
      { question: "Is this useful for a smaller service team too?", answer: "Yes, if the same process repeats often enough that manual coordination is already affecting capacity or quality." },
      { question: "Does the system need to cover every case type from day one?", answer: "No. It is often better to start with one workflow or the most painful operational area first." },
      { question: "Can it connect to the rest of the company stack?", answer: "Yes. For service operations that integration is often important to speed and reliability." },
    ],
    related: ["service-internal-tools-development", "service-ai-automation-and-integrations", "use-case-ai-intake-triage", "use-case-workflow-automation-tools", "problem-replace-spreadsheets-in-process", "inquiry"],
    fitFor: ["service or operations teams with recurring workflow", "companies trying to reduce manual coordination and improve visibility", "processes with several roles, deadlines, and exception paths"],
    fitNot: ["simple tracking with no real workflow", "projects with no owner of the service process", "cosmetic redesigns with no operational change"],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-ai-internal-documents",
    locale: "cs",
    slug: "ai-nad-internimi-dokumenty",
    title: "AI nad interními dokumenty a znalostmi firmy",
    h1: "AI nad interními dokumenty a znalostmi firmy",
    description:
      "Příklad využití AI nad interními dokumenty a znalostmi firmy pro rychlejší dohledání informací, lepší onboarding a menší závislost týmu na ručním předávání znalostí.",
    primaryQuery: "ai nad interními dokumenty",
    heroTitle: "Najít správnou informaci místo jejího zdlouhavého dohledávání",
    heroSubtitle:
      "Vhodné tam, kde tým tráví čas hledáním odpovědí v dokumentech, poznámkách, návodech nebo roztříštěných interních materiálech.",
    intro: [
      "Firmy často mají důležité informace rozptýlené v dokumentech, e-mailech, poznámkách a hlavách lidí. Problém pak není jen dostupnost informací, ale i čas, který jejich dohledání stojí.",
      "AI dává v tomto use casu smysl jako vrstva nad existujícími dokumenty nebo interní znalostní bází. Ne jako náhrada procesu, ale jako rychlejší cesta k tomu, co už ve firmě existuje.",
    ],
    scenarios: [
      "noví lidé se dlouho orientují v interních materiálech",
      "support nebo obchod opakovaně dohledává stejné informace",
      "návody, dokumenty a pravidla jsou rozptýlené v několika úložištích",
      "firma je závislá na konkrétních lidech, kteří vědí, kde co najít",
    ],
    includes: [
      "návrh AI vrstvy nad dokumenty nebo interní knowledge base",
      "napojení na interní zdroje a relevantní dokumenty",
      "omezení odpovědí na určený kontext a zdroje",
      "ověření prvního provozního scénáře a návaznost na týmové workflow",
    ],
    outcomes: [
      "rychlejší dohledání informací v interních materiálech",
      "menší závislost na ručním předávání znalostí",
      "lepší onboarding a podpora interních týmů",
      "silnější základ pro další práci s dokumenty a interní znalostí",
    ],
    faq: [
      { question: "Musí být všechny dokumenty perfektně připravené?", answer: "Nemusí, ale čím lepší je struktura a kvalita podkladů, tím spolehlivější bývá výsledek. Často dává smysl začít jen vybranou částí dokumentace." },
      { question: "Je to vhodné i bez plnohodnotné knowledge base?", answer: "Ano. V řadě případů lze začít nad dokumenty, návody nebo interními materiály, které už firma má, a teprve postupně zlepšovat jejich strukturu." },
      { question: "Nahradí to zkušené lidi v týmu?", answer: "Ne. Cílem je zkrátit dohledávání a snížit rutinní závislost na konkrétních lidech, ne nahradit jejich know-how." },
    ],
    related: [
      "service-ai-automation-and-integrations",
      "service-internal-tools-development",
      "problem-ai-in-business-process",
      "guide-when-ai-integration-makes-sense",
      "use-case-service-team-ops-system",
      "inquiry",
    ],
    fitFor: [
      "firmy s dokumenty, návody a interními znalostmi rozptýlenými mezi nástroji",
      "týmy, které opakovaně hledají stejné odpovědi",
      "situace, kde je potřeba zrychlit onboarding nebo interní podporu",
    ],
    fitNot: [
      "projekty bez použitelných interních zdrojů",
      "očekávání, že AI nahradí chybějící dokumentaci úplně sama",
      "use case bez ownera interního obsahu a odpovědnosti za zdroje",
    ],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-ai-internal-documents",
    locale: "en",
    slug: "ai-over-internal-documents",
    title: "AI over internal documents and company knowledge",
    h1: "AI over internal documents and company knowledge",
    description:
      "An example of using AI over internal documents and company knowledge to speed up information retrieval, improve onboarding, and reduce dependence on manual knowledge transfer.",
    primaryQuery: "ai over internal documents",
    heroTitle: "Find the right answer instead of wasting time searching for it",
    heroSubtitle:
      "A strong fit where teams lose time searching through documents, notes, playbooks, or fragmented internal materials.",
    intro: [
      "Companies often keep important knowledge spread across documents, emails, notes, and individual people. The problem is not only access, but the time it takes to find the right answer.",
      "AI works well here as a layer over existing documents or an internal knowledge base. Not as a replacement for the process, but as a faster route to knowledge the company already has.",
    ],
    scenarios: [
      "new team members need too long to navigate internal materials",
      "support or sales repeatedly search for the same answers",
      "guides, rules, and documents are spread across several locations",
      "the company depends on specific people who know where things are",
    ],
    includes: [
      "design of an AI layer over documents or internal knowledge content",
      "integration with selected internal sources and materials",
      "grounding responses in approved context and sources",
      "validation of the first production scenario and team workflow fit",
    ],
    outcomes: [
      "faster access to internal information",
      "less dependence on manual knowledge transfer",
      "better onboarding and internal team support",
      "a stronger base for future document and knowledge workflows",
    ],
    faq: [
      { question: "Do all documents need to be perfectly structured?", answer: "No, but the better the source quality and structure, the more reliable the result tends to be. It often makes sense to start with one selected part of the knowledge set." },
      { question: "Is this useful without a formal knowledge base?", answer: "Yes. Many teams can start with the documents, guides, and internal materials they already have and improve the structure over time." },
      { question: "Does this replace experienced people?", answer: "No. The goal is to reduce repetitive lookup work and dependency on manual knowledge transfer, not to replace team expertise." },
    ],
    related: [
      "service-ai-automation-and-integrations",
      "service-internal-tools-development",
      "problem-ai-in-business-process",
      "guide-when-ai-integration-makes-sense",
      "use-case-service-team-ops-system",
      "inquiry",
    ],
    fitFor: [
      "companies with fragmented internal knowledge across tools",
      "teams repeatedly searching for the same answers",
      "situations where onboarding or internal support needs to be faster",
    ],
    fitNot: [
      "projects with no usable internal source material",
      "expecting AI to replace missing documentation on its own",
      "use cases with no owner of internal content quality",
    ],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-ai-intake-triage",
    locale: "cs",
    slug: "ai-zpracovani-prichozi-agendy",
    title: "AI zpracování příchozí agendy a požadavků",
    h1: "AI zpracování příchozí agendy a požadavků",
    description:
      "Příklad využití AI pro třídění a zpracování příchozí agendy, e-mailů nebo požadavků tam, kde firma potřebuje omezit ruční přeposílání, doplňování dat a zdržení v operativě.",
    primaryQuery: "ai zpracování příchozí agendy",
    heroTitle: "Příchozí agenda bez ručního třídění a přeposílání mezi lidmi",
    heroSubtitle:
      "Vhodné pro support, servis, backoffice nebo jiné týmy, kde se opakují podobné požadavky a ruční třídění začíná brzdit provoz.",
    intro: [
      "Typická situace je jednoduchá: e-maily, formuláře nebo požadavky přicházejí na jedno místo a lidé je pak ručně čtou, třídí, přeposílají a doplňují do dalších systémů.",
      "AI může v takovém workflow fungovat jako první vrstva pro klasifikaci, doplnění kontextu nebo předpřipravení dalšího kroku. Smysl ale dává hlavně tehdy, když navazuje na jasný proces a odpovědnosti.",
    ],
    scenarios: [
      "příchozí e-maily a požadavky se ručně třídí mezi více lidí nebo týmů",
      "stejné typy požadavků se opakují a mají podobný další postup",
      "operativa ztrácí čas doplňováním dat do CRM, ticketingu nebo interního systému",
      "firma potřebuje rychlejší reakci a menší chybovost v první fázi zpracování",
    ],
    includes: [
      "návrh AI vrstvy pro třídění, klasifikaci nebo přípravu dalšího kroku",
      "napojení na e-mail, formulář, ticketing nebo interní systém",
      "doplnění pravidel, validace a předání člověku tam, kde je potřeba",
      "ověření prvního use case a ladění podle reálných požadavků",
    ],
    outcomes: [
      "méně ruční práce v první fázi zpracování agendy",
      "rychlejší přiřazení požadavků správnému týmu nebo procesu",
      "nižší chybovost při třídění a přepisu dat",
      "lepší základ pro další workflow automatizaci",
    ],
    faq: [
      { question: "Je to vhodné i pro menší objem požadavků?", answer: "Ano, pokud je ruční třídění opakované, bere lidem čas a zdržuje další kroky. Nemusí jít jen o velké call centrum." },
      { question: "Musí AI rozhodovat úplně sama?", answer: "Ne. Často je lepší, když připraví návrh, doplní kontext nebo zařazení a finální kontrolu si v kritických situacích nechá člověk." },
      { question: "Lze to napojit na existující systémy?", answer: "Ano. Právě návaznost na ticketing, CRM, interní systém nebo další workflow bývá klíčová pro reálný přínos." },
    ],
    related: [
      "service-ai-automation-and-integrations",
      "service-automations-and-integrations",
      "problem-ai-in-business-process",
      "guide-when-ai-integration-makes-sense",
      "use-case-service-team-ops-system",
      "inquiry",
    ],
    fitFor: [
      "support, servis nebo backoffice s opakovanou příchozí agendou",
      "firmy, kde se požadavky ručně třídí a přeposílají mezi rolemi",
      "procesy, kde AI může urychlit první fázi workflow bez ztráty kontroly",
    ],
    fitNot: [
      "jednorázové požadavky bez opakovatelného vzoru",
      "proces bez návazného workflow nebo systému pro další krok",
      "očekávání plně autonomního rozhodování bez lidské kontroly tam, kde to nedává smysl",
    ],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-ai-intake-triage",
    locale: "en",
    slug: "ai-intake-processing-and-triage",
    title: "AI intake processing and request triage",
    h1: "AI intake processing and request triage",
    description:
      "An example of using AI for incoming-request triage, email handling, or intake processing where the company needs to reduce manual forwarding, repeated data entry, and delays in operations.",
    primaryQuery: "ai intake processing",
    heroTitle: "Incoming work without manual triage and endless forwarding",
    heroSubtitle:
      "A strong fit for support, service, back-office, or similar teams where repeated request types are slowing down operations.",
    intro: [
      "The pattern is common: emails, forms, or requests arrive in one place, and people then read them manually, classify them, forward them, and copy the necessary details into other tools.",
      "AI can work here as a first layer for classification, enrichment, or next-step preparation. It creates the most value when it is tied to a clear process and responsibility model.",
    ],
    scenarios: [
      "incoming emails and requests are manually routed between several people or teams",
      "the same request types repeat and follow similar next steps",
      "operations teams lose time entering data into CRM, ticketing, or internal tools",
      "the business needs faster response and lower error rate in the first handling stage",
    ],
    includes: [
      "design of an AI layer for triage, classification, or next-step preparation",
      "integration with email, forms, ticketing, or internal tools",
      "rules, validation, and handoff to people where needed",
      "first use-case validation and refinement based on real requests",
    ],
    outcomes: [
      "less manual work in the first intake stage",
      "faster routing to the right team or workflow",
      "lower error rate in classification and data transfer",
      "a better base for further workflow automation",
    ],
    faq: [
      { question: "Is this useful for smaller request volumes too?", answer: "Yes, if the manual sorting is repetitive, consumes time, and slows down the next step. It does not need to be a large support centre." },
      { question: "Does AI need to decide everything on its own?", answer: "No. In many cases it is better for AI to prepare classification or context while critical cases still keep a human validation step." },
      { question: "Can this connect to current systems?", answer: "Yes. The integration with ticketing, CRM, internal tools, or the rest of the workflow is usually what makes the solution actually valuable." },
    ],
    related: [
      "service-ai-automation-and-integrations",
      "service-automations-and-integrations",
      "problem-ai-in-business-process",
      "guide-when-ai-integration-makes-sense",
      "use-case-service-team-ops-system",
      "inquiry",
    ],
    fitFor: [
      "support, service, or back-office teams with recurring intake work",
      "companies manually routing requests between roles",
      "processes where AI can accelerate the first workflow stage without removing control",
    ],
    fitNot: [
      "one-off requests with no recurring pattern",
      "processes with no downstream workflow or system",
      "expecting fully autonomous decisions where human review is still needed",
    ],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-request-offer-delivery-system",
    locale: "cs",
    slug: "system-pro-poptavky-nabidky-a-realizaci",
    title: "Systém pro poptávky, nabídky a realizaci zakázek",
    h1: "Systém pro poptávky, nabídky a realizaci zakázek",
    description: "Příklad interního systému pro firmy, které potřebují propojit evidenci poptávek, tvorbu nabídek a následnou realizaci zakázek bez chaosu mezi obchodem a provozem.",
    primaryQuery: "systém pro poptávky nabídky a realizaci",
    heroTitle: "Jeden systém místo tabulek, e-mailů a ručního dohledávání zakázek",
    heroSubtitle: "Vhodné pro firmy, kde se nad jednou zakázkou potkává obchod, příprava nabídky a následná realizace.",
    intro: [
      "Tento typ systému dává smysl tam, kde firma nechce řídit zakázku ve třech oddělených světech. Poptávka, nabídka i realizace na sebe navazují a lidé potřebují pracovat nad jedním přehledem.",
      "Typický cíl není digitalizovat všechno najednou, ale dát obchodní a realizační části procesu jeden společný rámec, stavy a návaznost dalších kroků.",
    ],
    scenarios: [
      "poptávka přichází e-mailem nebo formulářem a dál se zpracovává ručně",
      "nabídka vzniká mimo hlavní evidenci a ztrácí se návaznost na zakázku",
      "po schválení nabídky přechází informace do realizace neúplně nebo ručně",
      "stav zakázky není snadno dohledatelný napříč obchodem a provozem",
    ],
    includes: [
      "evidence poptávek a jejich stavů",
      "návaznost nabídky na konkrétní poptávku",
      "převod do realizace a řízení dalšího průběhu",
      "přehled odpovědnosti, termínů, historie a poznámek",
      "možnost napojení na další firemní nástroje",
    ],
    outcomes: [
      "lepší přehled nad celým průchodem zakázky",
      "méně ruční koordinace mezi obchodem a realizací",
      "nižší riziko ztracených informací a nejasných stavů",
      "silnější základ pro další reporting nebo automatizaci",
    ],
    faq: [
      { question: "Je to vhodné jen pro velké firmy?", answer: "Ne. Smysl to má i pro menší firmu, pokud se proces opakuje dost často a současné řešení už začíná být nepřehledné." },
      { question: "Musí se řešit celý proces najednou?", answer: "Nemusí. Často dává smysl začít jednou etapou, například evidencí poptávek a převodem do realizace." },
      { question: "Lze systém rozšířit i později?", answer: "Ano. Dobře navržený interní systém se dá rozšiřovat podle toho, jak se proces ve firmě vyvíjí." },
    ],
    related: [
      "service-request-offer-delivery-system",
      "service-internal-tools-development",
      "service-automations-and-integrations",
      "problem-requests-offers-delivery-in-spreadsheets",
      "problem-replace-spreadsheets-in-process",
      "inquiry",
    ],
    fitFor: [
      "firmy se zakázkovým obchodem a navazující realizací",
      "týmy, kde se propojuje poptávka, nabídka a zakázka",
      "procesy, které už přerůstají tabulky a e-mail",
    ],
    fitNot: [
      "jednoduchá evidence bez návaznosti více kroků",
      "čistě CRM-only proces bez realizace",
      "týmy, které nechtějí popsat skutečný průběh procesu",
    ],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-request-offer-delivery-system",
    locale: "en",
    slug: "system-for-requests-offers-and-delivery",
    title: "System for requests, offers, and delivery jobs",
    h1: "System for requests, offers, and delivery jobs",
    description: "An internal-system example for companies that need to connect incoming requests, offer preparation, and delivery work without chaos between sales and operations.",
    primaryQuery: "system for requests offers and delivery",
    heroTitle: "One system instead of spreadsheets, emails, and manual job tracking",
    heroSubtitle: "A strong fit for companies where sales, offer preparation, and delivery all touch the same job.",
    intro: [
      "This kind of system makes sense where the company no longer wants to run the same job across three disconnected worlds. The request, offer, and delivery stages all depend on each other and need one shared operational view.",
      "The goal is not to digitise everything at once. The goal is to give the sales and delivery sides of the process one structure, one set of states, and clearer next-step continuity.",
    ],
    scenarios: [
      "the incoming request arrives by email or form and is processed manually from there",
      "the offer is prepared outside the main tracking flow and loses continuity with the job",
      "after approval, information moves into delivery incompletely or by hand",
      "job status is hard to understand across sales and operations",
    ],
    includes: [
      "tracking of incoming requests and their statuses",
      "clear link between the request and the offer",
      "conversion into delivery and tracking of the next phase",
      "visibility into ownership, deadlines, history, and notes",
      "possible integration with other company tools",
    ],
    outcomes: [
      "better visibility across the full job lifecycle",
      "less manual coordination between sales and delivery",
      "lower risk of lost information and unclear status",
      "stronger foundation for reporting or future automation",
    ],
    faq: [
      { question: "Is this only useful for large companies?", answer: "No. It also makes sense for smaller companies when the process repeats often enough that the current setup is already becoming hard to manage." },
      { question: "Does the full process need to be built at once?", answer: "No. It is often better to begin with one stage, such as request tracking and handoff into delivery." },
      { question: "Can the system be expanded later?", answer: "Yes. A well-designed internal system can grow as the company’s process becomes more mature." },
    ],
    related: [
      "service-request-offer-delivery-system",
      "service-internal-tools-development",
      "service-automations-and-integrations",
      "problem-requests-offers-delivery-in-spreadsheets",
      "problem-replace-spreadsheets-in-process",
      "inquiry",
    ],
    fitFor: [
      "companies with request-based sales and delivery work",
      "teams connecting requests, offers, and execution",
      "processes already outgrowing spreadsheets and email",
    ],
    fitNot: [
      "simple tracking with no multi-step continuity",
      "CRM-only processes with no delivery stage",
      "teams unwilling to describe the real operating process",
    ],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-request-offer-delivery-workflow",
    locale: "cs",
    slug: "workflow-poptavka-nabidka-realizace",
    title: "Workflow pro poptávku, nabídku a realizaci zakázky",
    h1: "Workflow pro poptávku, nabídku a realizaci zakázky",
    description: "Příklad jednoduchého interního systému pro firmy, které potřebují propojit poptávku, nabídku a realizaci zakázky do jednoho přehledu místo tabulek a e-mailu.",
    primaryQuery: "workflow poptávka nabídka realizace",
    heroTitle: "Jeden přehled místo rozpadlého procesu mezi obchodem a realizací",
    heroSubtitle: "Vhodné pro týmy, kde se jedna zakázka pohybuje mezi obchodem, nabídkou a následnou realizací.",
    intro: [
      "Tento typ systému dává smysl tam, kde firma nechce držet jednu zakázku ve třech oddělených světech. Poptávka, nabídka i realizace na sebe navazují a lidé potřebují pracovat nad jedním přehledem.",
      "Typický cíl není digitalizovat všechno najednou, ale dát celému průchodu jeden společný rámec, stavy a návaznost dalších kroků.",
    ],
    scenarios: [
      "poptávka přichází e-mailem nebo formulářem a dál se zpracovává ručně",
      "nabídka vzniká mimo hlavní evidenci a ztrácí se návaznost na zakázku",
      "po schválení nabídky přechází informace do realizace neúplně nebo ručně",
      "stav zakázky není snadno dohledatelný napříč obchodem a provozem",
    ],
    includes: [
      "evidence poptávek a jejich stavů",
      "návaznost nabídky na konkrétní poptávku",
      "převod do realizace a řízení dalšího průběhu",
      "přehled odpovědnosti, termínů, historie a poznámek",
      "možnost napojení na další firemní nástroje",
    ],
    outcomes: [
      "lepší přehled nad celým průchodem zakázky",
      "méně ruční koordinace mezi obchodem a realizací",
      "nižší riziko ztracených informací a nejasných stavů",
      "silnější základ pro další reporting nebo automatizaci",
    ],
    faq: [
      { question: "Je to vhodné jen pro velké firmy?", answer: "Ne. Smysl to má i pro menší firmu, pokud se proces opakuje dost často a současné řešení už začíná být nepřehledné." },
      { question: "Musí se řešit celý proces najednou?", answer: "Nemusí. Často dává smysl začít jednou etapou, například evidencí poptávek a převodem do realizace." },
      { question: "Lze systém rozšířit i později?", answer: "Ano. Dobře navržený interní systém se dá rozšiřovat podle toho, jak se proces ve firmě vyvíjí." },
    ],
    related: [
      "service-request-offer-delivery-system",
      "service-internal-tools-development",
      "service-automations-and-integrations",
      "problem-requests-offers-delivery-in-spreadsheets",
      "problem-replace-spreadsheets-in-process",
      "inquiry",
    ],
    fitFor: [
      "firmy se zakázkovým obchodem a navazující realizací",
      "týmy, kde se propojuje poptávka, nabídka a zakázka",
      "procesy, které už přerůstají tabulky a e-mail",
    ],
    fitNot: [
      "jednoduchá evidence bez návaznosti více kroků",
      "čistě CRM-only proces bez realizace",
      "týmy, které nechtějí popsat skutečný průběh procesu",
    ],
  }),
  defineGrowthUseCasePage({
    translationKey: "use-case-request-offer-delivery-workflow",
    locale: "en",
    slug: "request-offer-delivery-workflow",
    title: "How a small team manages requests, offers and jobs in one system",
    h1: "How a small team manages requests, offers and jobs in one system",
    description: "An example of a simple internal system for teams that need to connect requests, offers, and delivery jobs in one shared workflow instead of relying on spreadsheets and email.",
    primaryQuery: "request offer delivery workflow",
    heroTitle: "From scattered information to one clear workflow",
    heroSubtitle: "A simple system that connects requests, offers, and jobs in one place.",
    intro: [
      "A typical situation is simple: requests arrive via email or form, offers are created in documents, and delivery is tracked somewhere else.",
      "The result is no shared view, no clear flow, and constant manual coordination between people.",
    ],
    scenarios: [
      "requests arrive by email or form and are processed manually",
      "offers are created outside the main tracking flow",
      "approved work is handed over into delivery by hand",
      "job status is hard to understand across sales and operations",
    ],
    includes: [
      "request capture and status tracking",
      "offer linked to the request",
      "handoff into delivery with clear ownership",
      "history, notes, deadlines, and next-step visibility",
      "possible connection to other company tools",
    ],
    outcomes: [
      "clearer workflow from request to delivery",
      "less manual coordination between roles",
      "lower risk of lost information and outdated status",
      "better base for reporting or future automation",
    ],
    faq: [
      { question: "Is this only useful for large companies?", answer: "No. It also makes sense for smaller teams when the process repeats often enough that the current setup is already becoming hard to manage." },
      { question: "Does the full process need to be built at once?", answer: "No. It is often better to begin with one stage and expand from there." },
      { question: "Can the system be expanded later?", answer: "Yes. A well-designed internal system can grow as the workflow becomes more mature." },
    ],
    related: [
      "service-request-offer-delivery-system",
      "service-internal-tools-development",
      "service-automations-and-integrations",
      "problem-requests-offers-delivery-in-spreadsheets",
      "problem-replace-spreadsheets-in-process",
      "inquiry",
    ],
    fitFor: [
      "small teams managing request-to-delivery work",
      "companies connecting sales, offers, and execution",
      "processes already outgrowing spreadsheets and email",
    ],
    fitNot: [
      "simple tracking with no multi-step continuity",
      "CRM-only processes with no delivery stage",
      "teams unwilling to describe the real process",
    ],
  }),
];
